Added h5pydiff.py script and changed test_support to use it

diff --git a/test/common/test_support b/test/common/test_support
--- a/test/common/test_support
+++ b/test/common/test_support
@@ -46,7 +46,7 @@ check_output ()
 
     local file_a=$1
     local file_b=$2
-    local h5diff_flags=${@:3}
+    local h5pydiff_flags=${@:3}
     
     # If file_b isn't set, use ref file
 
@@ -70,21 +70,22 @@ check_output ()
     # still returns 0 if they are not comparable, so
     # this extra check is required)
 
-    ! h5diff -c $file_a $file_b | grep -q 'Not comparable'
-    retval=$?
+    # ! h5diff -c $file_a $file_b | grep -q 'Not comparable'
+    # retval=$?
 
-    if [ $retval -ne 0 ]; then
-	echo " ...failed: $file_a and $file_b are not comparable"
-	return $retval
-    fi
+    # if [ $retval -ne 0 ]; then
+    # 	echo " ...failed: $file_a and $file_b are not comparable"
+    # 	return $retval
+    # fi
 
     # Do the test
 
-    h5diff -q $h5diff_flags $file_a $file_b
+    #h5diff -q $h5diff_flags $file_a $file_b
+    ${GYRE_DIR}/test/common/h5pydiff.py $h5pydiff_flags $file_a $file_b
     retval=$?
 
     if [ $retval -ne 0 ]; then
-	h5diff -r $h5diff_flags $file_a $file_b
+#	h5diff -r $h5diff_flags $file_a $file_b
 	echo " ...failed: $file_a and $file_b differ"
     fi
 
